# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: gitso

builds:
  - id: gitso
    main: .
    env: [CGO_ENABLED=0]
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ if eq .Os \"darwin\" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
